# Generated by Django 3.0.8 on 2020-07-08 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('catagory', models.CharField(choices=[('MOTOROLA', 'MOTOROLA'), ('NOKIA', 'NOKIA'), ('VIVO', 'VIVO'), ('SAMSUNG', 'SAMSUNG'), ('APPLE', 'APPLE')], max_length=200)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=100, null=True)),
                ('memmory', models.CharField(blank=True, max_length=100, null=True)),
                ('battary', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.IntegerField()),
                ('delivary_type', models.BooleanField(default=False)),
                ('rating', models.ManyToManyField(related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Po',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('total_price', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now=True)),
                ('paymentmethod', models.CharField(default='cash on delivary', max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
    ]
