# Generated by Django 3.0.8 on 2020-07-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_remove_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avarage', models.ManyToManyField(blank=True, related_name='avarages', to=settings.AUTH_USER_MODEL)),
                ('bad', models.ManyToManyField(blank=True, related_name='bads', to=settings.AUTH_USER_MODEL)),
                ('excellent', models.ManyToManyField(blank=True, related_name='excellents', to=settings.AUTH_USER_MODEL)),
                ('good', models.ManyToManyField(blank=True, related_name='goods', to=settings.AUTH_USER_MODEL)),
                ('ok', models.ManyToManyField(blank=True, related_name='oks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
