# Generated by Django 3.0.8 on 2020-07-09 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20200709_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bad',
            field=models.ManyToManyField(blank=True, related_name='bads', to=settings.AUTH_USER_MODEL),
        ),
    ]
