# Generated by Django 3.0.8 on 2020-07-09 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_auto_20200709_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avarage',
            field=models.ManyToManyField(blank=True, related_name='avarages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='good',
            field=models.ManyToManyField(blank=True, related_name='goods', to=settings.AUTH_USER_MODEL),
        ),
    ]
