# Generated by Django 3.0.8 on 2020-07-09 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0008_auto_20200709_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avarage',
            field=models.ManyToManyField(blank=True, related_name='_product_avarage_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='bad',
            field=models.ManyToManyField(blank=True, related_name='_product_bad_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='good',
            field=models.ManyToManyField(blank=True, related_name='_product_good_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
