# Generated by Django 3.0.8 on 2020-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
