# Generated by Django 3.0.8 on 2020-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_cart_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cashondelivary',
            field=models.BooleanField(default=False),
        ),
    ]
