# Generated by Django 3.0.8 on 2020-07-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_cart_cashondelivary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='po',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='po',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='po',
            name='rejected_reason',
        ),
        migrations.AddField(
            model_name='cart',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
