# Generated by Django 3.0.8 on 2020-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(default='Product name not mentioned,refer product ID', max_length=100),
        ),
    ]
